export const moviesData = [
    {
        id: Math.random(),
        image: "https://melhoresfilmesdahistoriaemumano.files.wordpress.com/2015/01/220px-shawshankredemptionmovieposter.jpg",
        rating:5,
        name: "The Shawshank Redemption",
        date: "1994",
        description:"En 1947, Andy Dufresne, un jeune banquier, est condamné à la prison à vie pour le meurtre de sa femme et de son amant. Ayant beau clamer son innocence, il est emprisonné à `Shawshank', le pénitencier le plus sévère de l'Etat du Maine. Il y fait la rencontre de Red, un homme désabusé, détenu depuis 20 ans. Commence alors une grande histoire d'amitié entre les deux hommes.",
        trailer :"https://www.youtube.com/embed/6hB3S9bIaco",
    },

    {
        id: Math.random(),
        image:"https://upload.wikimedia.org/wikipedia/en/0/07/The_Wall_%282017_film%29.png",
        rating:4,
        name: "The Wall",
        date: "2017",
        description: "Two US soldiers are targeted by an Iraqi sniper. Only a ruined section of wall still protects them from certain death. Beyond a struggle for survival, it is a war of wills that is played out, made up of tactics, intelligence and the ability to reach the enemy by all means.",
        trailer :"https://www.youtube.com/embed/MyCuUr2_hmA" ,
    },
    {
        id: Math.random(),
        image: "https://upload.wikimedia.org/wikipedia/en/5/5a/Blooddiamondposter.jpg",
        rating:3,
        name: "Blood diamonds",
        date: "2006",
        description: "While serving a prison sentence for his trafficking, Archer meets Solomon Vandy, a fisherman of Mende origin. Torn from his family and forced to work in the diamond mines, the latter found - and hid - an extremely rare pink diamond. Accompanied by an idealistic journalist, the two men embark on a dangerous journey in rebel territory to recover the famous stone.",
        trailer :"https://www.youtube.com/embed/yknIZsvQjG4",
    },
    {
        id: Math.random(),
        image:"https://upload.wikimedia.org/wikipedia/en/thumb/a/ad/Accident_Man_film_poster.jpg/220px-Accident_Man_film_poster.jpg",
        rating:2,
        name: "Accident man",
        date: "2018",
        description: "Mike Gallon is a hired killer as discreet as he is efficient. His fate changes when he finds out that one of his colleagues is responsible for the murder of his ex-girlfriend.",
        trailer :"https://www.youtube.com/embed/8NT-4VIpv1k",
    },
    {
        id: Math.random(),
        image: "https://upload.wikimedia.org/wikipedia/en/1/1f/Dolittle_%282020_film_poster%29.png",
        rating:1,
        name: "Dolittle",
        date: "2020",
        description: "Doctor John Dolittle has the gift of communicating with animals.",
        trailer : "https://www.youtube.com/embed/FEf412bSPLs",
    },
];